name: Upload API Artifacts

on:
  workflow_call:
    secrets:
      MOTIF_UPLOAD_API_ARTIFACTS_ACCESS:
        required: true

jobs:
  build-upload-lib-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Motif repository using git
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build motif lib content
        run: npm run lib

      - name: Upload motif lib artifact
        uses: actions/upload-artifact@v4
        with:
          name: lib-output
          path: lib
